### ISSUE TITLE
controlcomponent - should `this.mapService.getMap(this.mapidService)` be `this.mapService.getMap(this.mapidService.getId())` instead?

### ISSUE THREAD

**Issue by umbe1987** [Viglino/ol-ext-angular#3]
I am not 100% sure about this, but, as I am using your examples in this repo (a LOT actually, thanks!), I came across [this line of code](https://github.com/Viglino/ol-ext-angular/blob/3d0c5950e22e459fbdae94ff2afea086a8dceaab/src/app/map/control/control.component.ts#L45) inside `control.component.ts`:

    const map: OlMap = this.mapService.getMap(this.mapidService || this.mapId);

Shouldn't it be:

    const map: OlMap = this.mapService.getMap(this.mapidService.getId() || this.mapId);

?

Anyway, big thanks for sharing this repo!!!

**Comment by Viglino** [comment]
It can be both.
The `getMap` method tests id and get the id if it is a service (otherwise uses it as id).

**Comment by umbe1987** [comment]
Totally right!
It's just that in my project I took out the auto id assignment.
thanks again for this neat repo.
closed.
