### ISSUE TITLE
Styling custom controls

### ISSUE THREAD

**Issue by umbe1987** [Viglino/ol-ext-angular#4]
Hello, and again thanks for this repo.

I would appreciate your help if you can answer.

I am having serious troubles in understanding how should I style a custom control.

I have defined my custom control like this:

**sync-control.ts**
```
import Control from 'ol/control/Control';

export class SyncControl extends Control {
    constructor() {
        const button = document.createElement('button');

        const element = document.createElement('div');
        element.className = 'sync-control';
        element.appendChild(button);

        super( { element } );
    }
}
```

**sync-control.component.ts**
```
import { Component, OnInit, Host } from '@angular/core';

import { MapService } from '../../map.service';
import { MapidService } from '../../mapid.service';
import { Map } from 'ol';
import { SyncControl } from './sync-control';

@Component({
  selector: 'app-sync-control',
  templateUrl: './sync-control.component.html',
  styleUrls: ['./sync-control.component.css']
})
export class SyncControlComponent implements OnInit {

  constructor(
    private mapService: MapService,
    @Host()
    private mapidService: MapidService) { }

  ngOnInit(): void {
    // Get the current map
    const map: Map = this.mapService.getMap(this.mapidService.getId());
    const control = new SyncControl();
    map.addControl(control);
  }

}
```

**sync-control.component.css**
```
.sync-button {
    background-color: blue;
}
```

**app.component.html**
```
<div class="map-wrapper">
    <div class="map-item">
        <h4>Origin</h4>
        <app-map id="origin" class="map">
            <app-sync-control></app-sync-control>
            <app-layer name="overlay"></app-layer>
        </app-map>
    </div>
</div>
```
I can see the control in the map, however, I cannot style it.

I also tried with inline style (i.e. `<app-sync-control style="background-color: blue;">`), but neither that worked.

**Comment by Viglino** [comment]
When using Angular, it will scope the style to the component to prevent style collision.
When adding a control to a map it will be inserted in the map not in your control component and the style won't apply.
Try to prevent style encapsulation using ViewEncapsulation.None to access the style outside the component:
```javascript
@Component({
  selector: 'app-sync-control',
  // Include ol style as global
  encapsulation: ViewEncapsulation.None,
  templateUrl: './sync-control.component.html',
  styleUrls: ['./sync-control.component.css']
})
```
See https://angular.io/api/core/ViewEncapsulation#None

**Comment by umbe1987** [comment]
Amazing! that worked perfectly.
many thanks for the fast feedback, I will now carefully read and (hopefully) understand ViewEncapsulation (although you just explained it to me in perfect summary :+1: )
