### ISSUE TITLE
Not getting vector layer displayed on map

### ISSUE THREAD

**Issue by tarangrathod** [Viglino/ol-ext-angular#6]
Hi, I tried to add some marker points using this example but after generating a vector layer with a feature layer map doesn't display any marker or text at all maybe I missed something very crucial while doing this code. 

**where I am moderating the following code**

_in app-layer-component added_
these two code in ngoninit hook
`case 'marker': {
        layer = new l.Vector({
          source: this.markerVSource
        });
        break;
      }`

` if (this.layer == 'marker') {
      const features = this.mapService.olPtsLayer()
      const mStyle = this.mapService.markerStyle();
      this.markerVSource.addFeatures(features)
      layer.setStyle(mStyle)
      layer.setVisible(this.visibility);
      layer.setOpacity(this.opacity);
      console.log(this.markerVSource.getFeatures())
    }`

_this declaration as a property_
`markerVSource = new s.Vector({
    features: [],
    attributions: 'National UFO Reporting Center',
  });`
and the rest code is exactly the same.
also, I tried to console log the feature layer after adding it to the map which shows the layer has been added but non of the markers appears. Tried testing its icon styles is at a valid path!
can you guide me on how can I add a marker using the app-layer-component
![image](https://user-images.githubusercontent.com/72619617/97451002-53952880-1959-11eb-9b11-b34b84441c24.png)

**Comment by Viglino** [comment]
Have you added the layer to the map?
Check the layer visibility...
Check the features coordinates...

**Comment by wavesMeetU** [comment]
@Viglino  hi yes i checked the above two points, its visibility set to true. Generating 100 different coordinates using a loop they all work with simple implementation I tested 
https://stackblitz.com/edit/ol-ext-angular-extend-x54sxn?file=src%2Fapp%2Fmap%2Flayer%2Flayer.component.ts please check this stackbiltz it has the code

**Comment by Viglino** [comment]
First you have to add the layer to your map in the appComponent:
```html
  <app-layer layer="marker"></app-layer>
```
Then it seems your coordinates are bad (y=NaN)
NB: ol is using lng/lat (not lat/lng) in from**LonLat**
```javascript
   var coords = fromLonLat([parseFloat(element.lng), parseFloat(element.lat)]);
```   
Then you have to check your coords...

**Comment by codespitter** [comment]
hey yes you are correct !! I just changed coordinates and it got fixed. thanks for big help and sorry for trouble I am new to ol and ol debugging skills.....!!! thanks again a great project by you.
